# NumPy

In [8]:
import numpy as np
import sys

Podstawy

In [19]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [11]:
b = np.array([[4.0,5.0,6.0],[7.0,8.0,9.0]])
print(b)

[[4 5 6]
 [7 8 9]]


In [25]:
print(a*b)

[[ 4 10 18]
 [ 7 16 27]]


In [14]:
# Get dimension
b.ndim

2

In [15]:
# Get shape
b.shape

(2, 3)

In [28]:
# Get type 
b.dtype

dtype('int32')

In [20]:
a.dtype

dtype('int16')

In [27]:
# Get size
b.itemsize

4

In [22]:
a.itemsize

2

In [26]:
# Get total size
b.nbytes

24

Manipulacja tabel w numpy.