# NumPy

In [2]:
import numpy as np
import sys

Podstawy

In [19]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [11]:
b = np.array([[4.0,5.0,6.0],[7.0,8.0,9.0]])
print(b)

[[4 5 6]
 [7 8 9]]


In [25]:
print(a*b)

[[ 4 10 18]
 [ 7 16 27]]


In [14]:
# Get dimension
b.ndim

2

In [15]:
# Get shape
b.shape

(2, 3)

In [28]:
# Get type 
b.dtype

dtype('int32')

In [20]:
a.dtype

dtype('int16')

In [27]:
# Get size
b.itemsize

4

In [22]:
a.itemsize

2

In [26]:
# Get total size
b.nbytes

24

Manipulacja tabel w numpy.

In [3]:
a = np.array([[1,2,3,4,5,6,7],[7,6,5,4,3,2,1]])
print(a)

[[1 2 3 4 5 6 7]
 [7 6 5 4 3 2 1]]


In [4]:
a.shape

(2, 7)

In [5]:
# Get a specific element
a[1, 5]

2

In [6]:
a.shape[1]

7

In [8]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
# Get a specific column
a[:, 2]

array([3, 5])

In [11]:
a[0, 1:7:2]

array([2, 4, 6])

In [15]:
a[1,5]=20
print(a)

a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 7  6  5  4  3 20  1]]
[[ 1  2  5  4  5  6  7]
 [ 7  6  5  4  3 20  1]]


Tablice 3-d.

In [19]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
# Get specific element (work outside in)
b[0,1,1]

4

In [24]:
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


Różne typy tablic w NumPy

In [26]:
# Macierz 0 
np.zeros()