# NumPy

In [2]:
import numpy as np
import sys

Podstawy

In [19]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [11]:
b = np.array([[4.0,5.0,6.0],[7.0,8.0,9.0]])
print(b)

[[4 5 6]
 [7 8 9]]


In [25]:
print(a*b)

[[ 4 10 18]
 [ 7 16 27]]


In [14]:
# Get dimension
b.ndim

2

In [15]:
# Get shape
b.shape

(2, 3)

In [28]:
# Get type 
b.dtype

dtype('int32')

In [20]:
a.dtype

dtype('int16')

In [27]:
# Get size
b.itemsize

4

In [22]:
a.itemsize

2

In [26]:
# Get total size
b.nbytes

24

Manipulacja tabel w numpy.

In [3]:
a = np.array([[1,2,3,4,5,6,7],[7,6,5,4,3,2,1]])
print(a)

[[1 2 3 4 5 6 7]
 [7 6 5 4 3 2 1]]


In [4]:
a.shape

(2, 7)

In [5]:
# Get a specific element
a[1, 5]

2

In [6]:
a.shape[1]

7

In [8]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
# Get a specific column
a[:, 2]

array([3, 5])

In [11]:
a[0, 1:7:2]

array([2, 4, 6])

In [15]:
a[1,5]=20
print(a)

a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 7  6  5  4  3 20  1]]
[[ 1  2  5  4  5  6  7]
 [ 7  6  5  4  3 20  1]]


Tablice 3-d.

In [19]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
# Get specific element (work outside in)
b[0,1,1]

4

In [24]:
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


Różne typy tablic w NumPy

In [30]:
# Macierz 0 
np.zeros((1,2))

array([[0., 0.]])

In [32]:
# Macierz 1
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [34]:
# Macierz innych liczb
np.full((2,2), 6, dtype='float32')

array([[6., 6.],
       [6., 6.]], dtype=float32)

In [35]:
# Macierz innych liczb ale pobieramy shape z innej tabeli
np.full_like(a, 4, dtype='float32')

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]], dtype=float32)

In [38]:
# Losowe liczby między 0 i 1
np.random.rand(4,2,3)
np.random.random_sample(a.shape)

array([[0.06699379, 0.89471329, 0.58472239, 0.5064443 , 0.43961656,
        0.24721584, 0.23950595],
       [0.37877848, 0.29725242, 0.06364882, 0.41825206, 0.37997742,
        0.95379593, 0.03016699]])

In [54]:
# Losowe integery z zakresu
np.random.randint(-4,8, size=(3,3))

array([[ 7,  3,  0],
       [ 5, -1,  4],
       [-2,  4,  6]])

In [56]:
# Macierz jednostkowa
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [62]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [65]:
arr1 = np.ones((5,5), dtype='int32')
z = np.zeros((3,3), dtype='int32')
z[1,1]=9

arr1[1:4, 1:4] = z
print(arr1)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Kopiowanie tabel

In [66]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [67]:
b[0] = 100
a

array([100,   2,   3])

NumPy poprzez znak = wskazuje tą samą tabelę za pomocą innej nazwy

In [68]:
a = np.array([1,2,3])
b = a.copy()

Matematyka


In [83]:
a = np.array([1,2,3,4], dtype='float32')
a

array([1., 2., 3., 4.], dtype=float32)

In [86]:
a += 2 
print(a)

[3. 4. 5. 6.]


In [87]:
a -= 3
print(a)

[0. 1. 2. 3.]


In [88]:
a *= 2
print(a)

[0. 2. 4. 6.]


In [112]:
a+2
a/2
a*2
a/3

array([0.       , 0.6666667, 1.3333334, 2.       ], dtype=float32)

In [113]:
b = np.array([1,2,3,0], dtype='float32')
a + b

array([1., 4., 7., 6.], dtype=float32)

In [114]:
a ** 2

array([ 0.,  4., 16., 36.], dtype=float32)

In [116]:
# Sinus/cosinus wartości
np.sin(a)
np.cos(a)

array([ 1.        , -0.41614684, -0.6536436 ,  0.96017027], dtype=float32)

Algebra liniowa


In [134]:
a = np.ones((2,2), dtype='float16')
print(a)

b = np.full((3,2), 2, dtype='float16')
print(b)

[[1. 1.]
 [1. 1.]]
[[2. 2.]
 [2. 2.]
 [2. 2.]]


In [122]:
# Iloczyn macierzy
iloabM = np.matmul(a,b)

In [125]:
# Znalezienie wyznacznika macierzy
c = np.identity(3)
np.linalg.det(c)

1.0

In [135]:
c = np.array([[3,4],[6,9]])
# Iloczyn skalarny macierzy
iloabD = np.dot(a,c)
print(iloabD)

[[ 9. 13.]
 [ 9. 13.]]


Statystyka


In [137]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
np.min(stats, axis=1)

array([1, 4])

In [142]:
np.max(stats, axis=1)

array([3, 6])

In [143]:
np.sum(stats, axis=1)

array([ 6, 15])

Reorganizacja tabel

In [146]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [149]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [150]:
# Stackowanie wektorów pionowo
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [167]:
# Stackowanie poziome
h1 = np.random.randint(0,8, size=(2,4))
h2 = np.zeros((2,4))

np.hstack((h1,h2))

array([[7., 4., 1., 3., 0., 0., 0., 0.],
       [2., 0., 2., 1., 0., 0., 0., 0.]])

Manipulacja danych na plikach


In [173]:
fileData = np.genfromtxt('data.txt', delimiter=',', dtype='int16')
print(fileData)

[[ 1  2  3  4  5  7 12 44 19 20]
 [ 8 90 15 33 26  1 29 76 11 11]
 [ 5 78 87 65 56 34 33 21 45 15]]
